### ISSUE TITLE
When the same events starts and ends at the same date, event card displays incorrect date

### ISSUE THREAD

**Issue by vaidotasp** [chingu-voyage7/Bears-Team-09#105]
`Event.js` component displays date that is incremented by one.

For example, if we have event starting and ending on Feb 24, Event.js component displays date as Feb 25.

**Comment by lkaratun** [comment]
Can't reproduce =( Here's what I see:
![image](https://user-images.githubusercontent.com/17469132/52251772-de540b00-28cc-11e9-8566-d6054fe8fe95.png)
![image](https://user-images.githubusercontent.com/17469132/52251792-f2980800-28cc-11e9-98a2-c1302d0410a8.png)

**Comment by vaidotasp** [comment]
That is weird, I will need to investigate further. While I am on that I will see if I can refactor the date formatting a bit to make it simpler. Do you think we should display time if there is no way for user to select actual time right now ? I mean in the event creation page.

**Comment by lkaratun** [comment]
That would be great! We should definitely take out the time until we implement a way to choose it.

**Comment by vaidotasp** [comment]
This has been fixed with the latest #106.
