### ISSUE TITLE
Make events dashboard

### ISSUE THREAD

**Issue by lkaratun** [chingu-voyage7/Bears-Team-09#16]

**Comment by vaidotasp** [comment]
So to implement events dashboard I was thinking users would be able to go to a page and search and see the events that they would be interested in "pairing up" or link to a "create new event" page.

To start with a simple dashboard, we need the basic API endpoints:
Fetch events based on:
- Date (by default probably should fetch today - 30 days)
- Location (I am not sure how we are handling location in the backend, long/lat?) This should be a city. We could handle conversion on the front end if need be.
- Category. This would categorize events based on type (e.g. Outdoor, Games, Art, Sports, Social, etc) Have we decided on what those categories should be and what are the name of it ? Is it Category is it Activity ? 

Anything else that user should be able to search by?

@lkaratun @trolleksii

**Comment by lkaratun** [comment]
@vaidotasp  I think we can do location by city name for now, and connect smth like Google maps API later. 
For the activities, I think we could have categories like "sports", "arts and culture", etc. with more concrete activities in them: "Table tennis practice", "Music concert", "Museum visit", etc. It's ok if there is some overlap (an activity could belong to a couple categories), but there should be only 1 activity per dashboard entry. 

As for the endpoints, just hit up @trolleksii here or on slack, and I think he'll be able to make any endpoint for you =)

**Comment by vaidotasp** [comment]
Okay I think I have enough to go by here in order to start thinking about layout. I can even hardcore categories on the front end in a simple list and display those. Eventually we would probably make an endpoint of all categories that come from back end. Same with activities too, google maps API can be fairly easy to implement, but I will focus on getting something on the page first.

**Comment by vaidotasp** [comment]
I am not sure I understand a what is a "place" in the context of our app. I understand categories to be categories of the events (sports, arts and culture, etc). What is the place? Is that a geographical location (lon, lat coordinates) that the event is taking place?

**Comment by trolleksii** [comment]
We will start with simple Place object, when you query API for it you'll receive something like this:
`{
    country: "Canada",
    city: "Toronto"
}`
Later on we'll try to add GPS coordinates, so it will be somewhat like this:
`{
    country: "Canada", 
    city: "Toronto", 
    coordinates: [43.650864, -79.386529]
}`

**Comment by vaidotasp** [comment]
That makes sense. 
Speaking of Event Dashboard Page - Category and Place filters will work the same (at least in the beginning): **Client calls API to fetch all possible Categories and Places from DB** and displays them for user to choose. Upon those choices, client re-fetches event list that matches those criteria and displays them on the page.
That's the general idea?

**Comment by lkaratun** [comment]
Yes, this sounds good to me! Probably best do display 1 page of unfiltered results by default too.

**Comment by vaidotasp** [comment]
Yes, good idea. 10 events (or 5..I have no strong preference). We can implement one of those infinite scroll solutions, upon member scroll to the bottom > fetch another batch of events.
