### ISSUE TITLE
Add linting and styles?

### ISSUE THREAD

**Issue by vaidotasp** [chingu-voyage7/Bears-Team-09#2]
Hey Team,

I was thinking if we should add some standard code linting to the project so we can be on the same page.

I am a big fan of Prettier myself [https://prettier.io/](https://prettier.io/) which is a code formatter.
And also we could add ESLint [https://eslint.org/](https://eslint.org/ )with some basic rules.

What do we feel about that?

**Comment by lkaratun** [comment]
I'm all for using both ESLint (must-have IMO) and Prettier (kind of optional, but still nice to have).
I've been using [ESLint with Airbnb preset](https://gist.github.com/lkaratun/55cd99abfd68119b82a0b2dd6abcf8d4) (considered one of the best style guides by many developers) with several rules disabled. We can start using it and then disable some rules (or enabled the ones I disabled) as we go if we decide that they are doing more harm than good. 
Please let me know if that sounds reasonable.

**Comment by vaidotasp** [comment]
I'm good with that.

**Comment by vaidotasp** [comment]
Closing this as lining has been added. #8
