### ISSUE TITLE
CSS Approach

### ISSUE THREAD

**Issue by vaidotasp** [chingu-voyage7/Bears-Team-09#4]
What is team's opinion of CSS approach? 
Anybody want's to try something that they always wanted to learn, experiment,etc?
A whole bunch of choices are available for us:

- Flat CSS Files
- CSS Modules
- Styled Components
- Glamorous
- SASS
and so on...

I think at some point everybody will be touching frontend so it would be cool if we all be comfortable with the choice. Personally, I only used CSS Modules and Styled Components, I can do and learn whatever 👍

**Comment by lkaratun** [comment]
I have used SASS and a little bit of Styled components (would be glad to learn more) but am open to using something new (I would just prefer that it's something modern and popular)

**Comment by nealthom** [comment]
I have experience with SASS, but I am open to learning anything.

**Comment by vaidotasp** [comment]
I have put together a simple login page with styled components. I should be able to do a PR on that view later today so we can check it out and see how we feel about the approach.

**Comment by vaidotasp** [comment]
Hey team, so I want to start the conversation back up. If we are doing next.js we can assess if styled-components is something we want to do. Looks like some people get it working no problem, but it requires some setup:
https://dev.to/aprietof/nextjs--styled-components-the-really-simple-guide----101c

From the docs looks like Next comes with a library baked in:
https://nextjs.org/learn/basics/styling-components
https://github.com/zeit/styled-jsx

I can go whichever way we choose to, but I thought I bring this up.
@lkaratun @nealthom
