### ISSUE TITLE
Detect expired tokens on front end

### ISSUE THREAD

**Issue by lkaratun** [chingu-voyage7/Bears-Team-09#48]
Right now expired tokens don't allow requesting information from back end but there is no way of detecting the fact that it's expired. We could fix this by either supplying front end with expiration date when token is initially generated, or hard-coding it on front end, or replying with a more descriptive error when an expired token is used to request information from back end. There could be other solutions to this too. What does everyone think?

**Comment by trolleksii** [comment]
At least you will get 401 response for unauthorized requests. In my opinion it does not matter what is the exact reason for denial, if you got 401 - it means that user is not authenticated and you need to redirect to login page.

**Comment by lkaratun** [comment]
I think "Your session has expired" and "You are not logged in" are two different situations and should be distinguishable on the frontend. 

Related request: when backend can't connect to the DB, 401 is being returned. Can you change this to a 5** error code please? @trolleksii

**Comment by trolleksii** [comment]
@lkaratun 
500 is an 'Internal Server Error' nothing to deal with authentication.
All requests that failed to authenticate will respond with status code 401. What will differ is `message`.
In case if JWT expired:
```JSON
{
    "message": "jwt expired"
}
```
In case if there was no Authorization header at all or if the scheme name is not `bearer`:
```
{
    "message": "No auth token"
}
```
In case if token was malformed there are several options depending on the part of the token string where the error is:
```
{
    "message": "invalid token"
}
```
or
```
{
    "message": "invalid signature"
}
```
or
```
{
    "message": "jwt malformed"
}
```
Situation when Google token expired should not even occur at all.

**Comment by lkaratun** [comment]
Thanks for reminding me about the `message` field, we should make use of it on the front end. As we discussed on Skype, please make the server respond with 500 when it fails to connect to DB. @trolleksii

**Comment by vaidotasp** [comment]
Is this issue still valid?

**Comment by lkaratun** [comment]
@trolleksii have you had a chance to update back end to return 500 when DB connection fails?

**Comment by trolleksii** [comment]
Yes, its done
