### ISSUE TITLE
/events page not displaying events with no date

### ISSUE THREAD

**Issue by vaidotasp** [chingu-voyage7/Bears-Team-09#50]
Need to fix /events page to display all events that include expired (past-dated) and no-date events. Currently it does not do that but returns all events that are older than `today`.

**Comment by trolleksii** [comment]
1. Currently, date is optional. The main idea of this decision was that there may be events with date 'to be announced...'.
2. I think that chronological order makes perfect sense as a default. But it would be great to have a custom search and sort as well.
3. Pagination enabled with URL parameters, and in js would be implemented like that:
```
let pageNum = 0;
const pageSize = 5;
console.log(`http:\\backend.com:8000\events?orderby=date_from&offset=${pageNum * pageSize}&limit=${pageSize}`);
```

**Comment by vaidotasp** [comment]
Thanks for the input! So the correct way to do pagination in URL would be to multiply `pageNum` and `pageSize` ? 
The way I was doing was adding offset and limit, so it starts at 0 + 5 and then increments by 5, offset going up by 5 while limit staying at 5?
