### ISSUE TITLE
Question - Create new event should allow max 6 participants?

### ISSUE THREAD

**Issue by vaidotasp** [chingu-voyage7/Bears-Team-09#77]
Current create new event has selection of 2 to 6+ participants. Based on @lkaratun feedback I am going to change it to "6" instead of "6+". But this made me think, should be put caps and max participants, and if so - where? 

Are 2 -6 good? Or do we make it a bigger range? A free user entry?
@lkaratun @trolleksii 
<img width="357" alt="screen shot 2019-01-24 at 6 11 30 am" src="https://user-images.githubusercontent.com/12076555/51674561-f78cbb80-1f9e-11e9-8576-80fe193f0c5d.png">

**Comment by trolleksii** [comment]
I think free range is bulletproof, same style as `Min People`.

**Comment by trolleksii** [comment]
What about `Country` field?
It is in the db schema, and it is required to add a new `Place`, but we don't have this field in the form.

**Comment by vaidotasp** [comment]
> @vaidotasp , @lkaratun
> What about `Country` field?
> It is in the db schema, and it is required to add a new `Place`, but we don't have this field in the form.

That is a good point. I think we need to do a bit of work on the register form. Currently what frontend does is fetches all existing `places` from DB and only displays those. User is not able to create a new one. Ideally we want user to enter their location (City, Country) and if it does not exist, create new entry in DB. So yeah I agree about adding Country field, but we need to rework some of the logic there too. Worth opening new issue.

**Comment by lkaratun** [comment]
For the people field, I think it's a good idea to verify a number was entered. Something like `!isNaN(parseInt(<input value>))` should work fine

**Comment by vaidotasp** [comment]
Good point. Added to the #86 
Closing this issue.
