### ISSUE TITLE
Create event page cleanup

### ISSUE THREAD

**Issue by lkaratun** [chingu-voyage7/Bears-Team-09#86]
Several improvements need to be made to the "Create event" page:

- As discussed in #85, a field for bio should be added
- No way to switch focus to the activity picker
- Activity picker doesn't disappear when focus is switched to a different field
- The same issues with City picker
- The focused Activity/City should be picked on Enter press
- To make the interaction clear to the user, I think we should display the City picker immediately when the City field is focused
- On error, problematic fields should be clearly indicated
- Dynamic activity/place search 
- Option to add a new activity/place
- Allow submitting form with empty fields if they are not required by back end

**Comment by lkaratun** [comment]
Yep, this would be great to have too. I'll edit the original post

**Comment by vaidotasp** [comment]
Adding this validation to the list of enhancements:

In People field - verify a number was entered. 
"Something like !isNaN(parseInt(<input value>)) should work fine"

**Comment by vaidotasp** [comment]
> * As discussed in #85, a field for bio should be added

This should be probably moved into new issue for Register User and not for Create Event page? I think we mashed two ideas together :)

**Comment by vaidotasp** [comment]
I think that majority of issues has been addressed and we have a separate issue open for the bio field.
